name: ksivpn

x-service-defaults: &service-defaults
  restart: unless-stopped
  networks: [ksivpn]

services:
  ksivpn-tgbot:
    <<: *service-defaults
    container_name: ksivpn-tgbot
    build:
      context: .
      dockerfile: ./build/microservice/Dockerfile
    image: ${DOTENV_TGBOT_IMAGE}:${DOTENV_TGBOT_TAG}
    environment:
      TZ: ${DOTENV_TZ}
      BOT_TOKEN: ${DOTENV_TGBOT_BOT_TOKEN}
      PROXY_URL: ${DOTENV_TGBOT_PROXY_URL}
      POSTGRES_USER: ${DOTENV_POSTGRES_USER}
      POSTGRES_PASSWORD: ${DOTENV_POSTGRES_PASSWORD}
      POSTGRES_DB: ${DOTENV_POSTGRES_DB}
      REDIS_HOST: ksivpn-tgbot-redis
      REDIS_PORT: 6379
      REDIS_DB: 1
      REDIS_PASSWORD: ${DOTENV_REDIS_PASSWORD}
      FSM_PREFIX: ${DOTENV_TGBOT_REDIS_FSM_PREFIX}
      YOOMONEY_TOKEN: ${DOTENV_TGBOT_YOOMONEY_TOKEN}
      YOOMONEY_ACCOUNT_NUMBER: ${DOTENV_TGBOT_YOOMONEY_ACCOUNT}
      ADMIN_ID: ${DOTENV_TGBOT_ADMIN_ID}
      BACKUP_PATH: ${DOTENV_TGBOT_BACKUP_PATH}
      LOCALIZATION_LANGUAGE: ${DOTENV_TGBOT_LOCALIZATION_LANGUAGE}
    volumes: [ "ksivpn-tgbot-postgres-backups:${DOTENV_TGBOT_BACKUP_PATH}" ]
    depends_on:
      ksivpn-tgbot-postgres:
        condition: service_healthy
      ksivpn-tgbot-redis:
        condition: service_healthy

  ksivpn-tgbot-postgres:
    <<: *service-defaults
    container_name: ksivpn-tgbot-postgres
    build:
      context: ./build/postgres
      args:
        ADDITIONAL_LANGUAGE: ${DOTENV_POSTGRES_ADDITIONAL_LANGUAGE}
    image: ${DOTENV_POSTGRES_IMAGE}:${DOTENV_POSTGRES_TAG}
    environment:
      TZ: ${DOTENV_TZ}
      POSTGRES_USER: ${DOTENV_POSTGRES_USER}
      POSTGRES_PASSWORD: ${DOTENV_POSTGRES_PASSWORD}
      POSTGRES_DB: ${DOTENV_POSTGRES_DB}
      POSTGRES_INITDB_ARGS: ${DOTENV_POSTGRES_INITDB_ARGS}
    ports: [ "${DOTENV_POSTGRES_PORT}:5432" ]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DOTENV_POSTGRES_USER} -d ${DOTENV_POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
      start_interval: 1s
    volumes:
      - ksivpn-tgbot-postgres-data:/var/lib/postgresql/data
      - ksivpn-tgbot-postgres-backups:/var/lib/postgresql/backups

  ksivpn-tgbot-redis:
    <<: *service-defaults
    container_name: ksivpn-tgbot-redis
    image: redis:8.6.2-alpine3.23
    command:
      - redis-server
      - --requirepass
      - ${DOTENV_REDIS_PASSWORD}
      - --appendonly
      - "yes"
      - --save
      - "60"
      - "1000"
      - --loglevel
      - warning
    healthcheck:
      test: ["CMD-SHELL", "redis-cli --pass ${DOTENV_REDIS_PASSWORD} ping | grep -q PONG"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 5s
    volumes:
      - ksivpn-tgbot-redis-data:/data

networks:
  ksivpn:
    name: ksivpn

volumes:
  ksivpn-tgbot-postgres-data:
    name: ksivpn-tgbot-postgres-data
  ksivpn-tgbot-postgres-backups:
    name: ksivpn-tgbot-postgres-backups
  ksivpn-tgbot-redis-data:
    name: ksivpn-tgbot-redis-data
