from aiogram import F, Router
from aiogram.enums import ChatAction
from aiogram.filters import CommandStart, Command
from aiogram.fsm.context import FSMContext
from aiogram.types import Message, CallbackQuery
from src.keyboards import user_authorized_kb, user_unauthorized_kb, other_kb
from src.database import postgres_dbms
from src.services import gpt4free, internal_functions, localization as loc
from src.runtime import bot


global_router = Router(name="global_commands")
router = Router(name="other")


@global_router.message(CommandStart())
async def command_start(message: Message, state: FSMContext):
    """Send message when user press /start."""
    # if user isn't in db
    if not await postgres_dbms.is_user_registered(message.from_user.id):
        # send hello image with message
        # use safe sending in case new bot tries to send photo using ksiVPN's bot file_id
        await internal_functions.send_photo_safely(message.from_user.id,
                                                   telegram_file_id=loc.other.tfids['hello_message'],
                                                   caption=loc.other.msgs['hello_message'],
                                                   reply_markup=other_kb.faq_inline)

        # reset FSM state and show welcome keyboard
        await state.clear()
        await message.answer(loc.other.msgs['more_info'], reply_markup=user_unauthorized_kb.welcome)

    # if user is already in db
    else:
        # reset FSM state and show menu keyboard
        await state.clear()
        await message.answer(loc.other.msgs['restart'], reply_markup=user_authorized_kb.menu)


@global_router.message(Command(commands=['help']))
@global_router.message(F.text.lower() == loc.other.btns['help'].lower())
async def command_help(message: Message):
    """Send message with information about provided help (works in any FSM state)."""
    await internal_functions.send_photo_safely(message.from_user.id,
                                               telegram_file_id=loc.other.tfids['help'],
                                               caption=loc.other.msgs['help'])

    # if client needs to renew subscription before receiving his first configuration
    await internal_functions.notify_client_if_subscription_must_be_renewed_to_receive_configuration(message.from_user.id)


@global_router.message(F.text.lower() == loc.other.btns['about_project'].lower())
@global_router.message(F.text.lower() == loc.other.btns['about_service'].lower())
async def show_project_info(message: Message):
    """Send message with information about project (works in any FSM state)."""
    # use safe sending in case new bot tries to send photo using ksiVPN's bot file_id
    await internal_functions.send_photo_safely(message.from_user.id,
                                               telegram_file_id=loc.other.tfids['project_info'],
                                               caption=loc.other.msgs['project_info'],
                                               reply_markup=other_kb.faq_inline)
    # if client is registered
    if await postgres_dbms.is_user_registered(message.from_user.id):
        await message.answer(loc.other.msgs['special_thanks'])


@router.callback_query(F.data == loc.other.btns['faq_inline_callback'])
async def show_faq(call: CallbackQuery):
    """Send message with F.A.Q. information."""
    await call.message.answer(loc.other.msgs['faq_info'])
    await call.answer()


@router.message()
async def answer_unrecognized_messages(message: Message):
    """Answer unrecognized messages with template message or generated by gpt4free conscious message."""
    # if client is registered and client turns on ChatGPT mode for bot
    if await postgres_dbms.is_user_registered(message.from_user.id) and await postgres_dbms.get_chatgpt_mode_status(await postgres_dbms.get_clientID_by_telegramID(message.from_user.id)):

        # is client's subscription is active
        if await postgres_dbms.is_subscription_active(message.from_user.id) \
                or await postgres_dbms.is_subscription_free(message.from_user.id):

            await bot.send_chat_action(message.from_user.id, ChatAction.TYPING)
            await message.reply(await gpt4free.chatgpt_answer(message.text))

        else:
            await message.reply(loc.other.msgs['chatgpt_only_for_active_sub'])

    # if is not registered of client turns off ChatGPT mode for bot
    else:
        await message.reply(loc.other.msgs['unrecognized_message'])


def register_handlers_global(dp):
    """Attach the global_commands router — must be registered before all other routers."""
    dp.include_router(global_router)


def register_handlers_other(dp):
    """Attach the `other` router to the dispatcher (kept for backwards-compatible imports)."""
    dp.include_router(router)
