CREATE TABLE remnawave_internal_squads (
	id SMALLSERIAL PRIMARY KEY,
	squad_uuid UUID UNIQUE NOT NULL,
	name VARCHAR(64) NOT NULL,
	is_active BOOLEAN NOT NULL DEFAULT TRUE,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
